Repository loco-3d/crocoddyl, pull requests merged in 2020-01, with the labels that each got.

#660 Fixed CI-github CI issue for 16.04-Debug + added examples in CI-github
  .travis.yml
  .travis/build-and-test.sh
  examples/quadrupedal_walk_ubound.py
Labels: ci/cd

#662 Run examples as tests
  .travis/build-and-test.sh
  examples/CMakeLists.txt
Labels: ci/cd

#664 Added getter and setter functions for solvers + improved Python bindings
  bindings/python/crocoddyl/core/integrator/euler.hpp
  bindings/python/crocoddyl/core/solver-base.hpp
  include/crocoddyl/core/solver-base.hpp
  src/core/integrator/euler.cpp
  src/core/solver-base.cpp
  src/core/solvers/ddp.cpp
  src/core/utils/callbacks.cpp
Labels: enhancement

#668 Control-limited FDDP solver
  bindings/python/crocoddyl/__init__.py
  bindings/python/crocoddyl/core.hpp
  bindings/python/crocoddyl/core/solvers/box-fddp.hpp
  bindings/python/crocoddyl/utils/__init__.py
  include/crocoddyl/core/solvers/box-fddp.hpp
  src/CMakeLists.txt
  src/core/solvers/box-fddp.cpp
  src/core/solvers/fddp.cpp
Labels: feature proposal

#670 Add display of friction cone + created geometries only once
  bindings/python/crocoddyl/__init__.py
Labels: efficiency, python

#671 Change gap notation + improved diagnotic tools
  bindings/python/crocoddyl/__init__.py
  bindings/python/crocoddyl/core/solver-base.hpp
  bindings/python/crocoddyl/core/solvers/ddp.hpp
  examples/CMakeLists.txt
  examples/arm_manipulation.py
  examples/bipedal_walk.py
  examples/bipedal_walk_ubound.py
  examples/boxfddp_vs_boxddp.py
  examples/double_pendulum.py
  examples/log/boxfddp_vs_boxddp.log
  examples/quadrotor.py
  examples/quadrotor_ubound.py
  examples/quadrupedal_gaits.py
  examples/quadrupedal_walk_ubound.py
  include/crocoddyl/core/numdiff/action.hpp
  include/crocoddyl/core/solver-base.hpp
  include/crocoddyl/core/solvers/ddp.hpp
  include/crocoddyl/core/solvers/fddp.hpp
  src/core/solvers/box-ddp.cpp
  src/core/solvers/box-fddp.cpp
  src/core/solvers/ddp.cpp
  src/core/solvers/fddp.cpp
Labels: python
