Repository loco-3d/crocoddyl, pull requests merged in 2020-07, with the labels that each got.

#793 Added whole-body manipulation notebook
  README.md
  examples/notebooks/whole_body_manipulation.ipynb
Labels: documentation, python

#802 Fix memory leaks in vector and map converters #795
  bindings/python/crocoddyl/core/numdiff/diff-action.cpp
  bindings/python/crocoddyl/core/optctrl/shooting.cpp
  bindings/python/crocoddyl/core/solver-base.cpp
  bindings/python/crocoddyl/crocoddyl.cpp
  bindings/python/crocoddyl/multibody/contacts/multiple-contacts.cpp
  bindings/python/crocoddyl/multibody/costs/cost-sum.cpp
  bindings/python/crocoddyl/multibody/impulses/multiple-impulses.cpp
  bindings/python/crocoddyl/utils/__init__.py
  bindings/python/crocoddyl/utils/map-converter.hpp
  bindings/python/crocoddyl/utils/vector-converter.hpp
Labels: bug, python

#792 CoP cost
  bindings/python/crocoddyl/multibody/costs/contact-cop-position.cpp
  bindings/python/crocoddyl/multibody/frames.cpp
  bindings/python/crocoddyl/multibody/multibody.cpp
  bindings/python/crocoddyl/multibody/multibody.hpp
  include/crocoddyl/multibody/costs/contact-cop-position.hpp
  include/crocoddyl/multibody/costs/contact-cop-position.hxx
  include/crocoddyl/multibody/frames.hpp
  include/crocoddyl/multibody/fwd.hpp
  src/multibody/costs/contact-cop-position.cpp
  unittest/bindings/CMakeLists.txt
  unittest/bindings/test_cop_cost.py
Labels: enhancement, feature proposal
