Repository loco-3d/crocoddyl, pull requests merged in 2023-01, with the labels that each got.

#1113 Fixed bug in the computation of terminal control cost
  examples/log/bipedal_walk_invdyn.log
  examples/log/bipedal_walk_ubound.log
  examples/log/humanoid_manipulation.log
  examples/log/quadrupedal_gaits_fwddyn.log
  examples/log/quadrupedal_gaits_invdyn.log
  include/crocoddyl/core/costs/residual.hxx
  include/crocoddyl/core/residuals/control.hxx
  include/crocoddyl/core/residuals/joint-acceleration.hxx
Labels: bug

#1093 Finite difference based computation of Lxx and Luu inside NumdiffDifferentialActionModel
  .github/workflows/industrial_ci_action.yml
  CMakeLists.txt
  README.md
  bindings/python/crocoddyl/core/numdiff/action.cpp
  bindings/python/crocoddyl/core/numdiff/activation.cpp
  bindings/python/crocoddyl/core/numdiff/diff-action.cpp
  bindings/python/crocoddyl/core/numdiff/state.cpp
  bindings/python/crocoddyl/core/residuals/joint-effort.cpp
  doc/Doxyfile.extra.in
  examples/log/boxfddp_vs_boxddp.log
  examples/log/quadrupedal_gaits_fwddyn.log
  examples/log/quadrupedal_gaits_invdyn.log
  examples/log/quadrupedal_walk_ubound.log
  include/crocoddyl/core/numdiff/action.hpp
  include/crocoddyl/core/numdiff/action.hxx
  include/crocoddyl/core/numdiff/activation.hpp
  include/crocoddyl/core/numdiff/activation.hxx
  include/crocoddyl/core/numdiff/actuation.hpp
  include/crocoddyl/core/numdiff/actuation.hxx
  include/crocoddyl/core/numdiff/constraint.hpp
  include/crocoddyl/core/numdiff/constraint.hxx
  include/crocoddyl/core/numdiff/control.hpp
  include/crocoddyl/core/numdiff/control.hxx
  include/crocoddyl/core/numdiff/cost.hpp
  include/crocoddyl/core/numdiff/cost.hxx
  include/crocoddyl/core/numdiff/diff-action.hpp
  include/crocoddyl/core/numdiff/diff-action.hxx
  include/crocoddyl/core/numdiff/residual.hpp
  include/crocoddyl/core/numdiff/residual.hxx
  include/crocoddyl/core/numdiff/state.hpp
  include/crocoddyl/core/numdiff/state.hxx
  include/crocoddyl/core/residuals/joint-effort.hpp
  include/crocoddyl/multibody/actions/impulse-fwddyn.hpp
  include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
  include/crocoddyl/multibody/numdiff/contact.hpp
  include/crocoddyl/multibody/numdiff/contact.hxx
  unittest/factory/diff_action.cpp
  unittest/test_actions.cpp
  unittest/test_activations.cpp
  unittest/test_actuation.cpp
  unittest/test_constraint_manager.cpp
  unittest/test_constraints.cpp
  unittest/test_contact_constraints.cpp
  unittest/test_contact_costs.cpp
  unittest/test_contacts.cpp
  unittest/test_controls.cpp
  unittest/test_cost_sum.cpp
  unittest/test_costs.cpp
  unittest/test_costs_collision.cpp
  unittest/test_costs_noFF.cpp
  unittest/test_diff_actions.cpp
  unittest/test_impulse_constraints.cpp
  unittest/test_impulse_costs.cpp
  unittest/test_residuals.cpp
  unittest/test_states.cpp
  unittest/unittest_common.hpp
Labels: enhancement, feature proposal

#1114 Extended residual API to define activation/residual multiplications + included in the cost residual
  bindings/python/crocoddyl/core/costs/residual.cpp
  bindings/python/crocoddyl/core/residual-base.cpp
  bindings/python/crocoddyl/core/residual-base.hpp
  examples/log/bipedal_walk_fwddyn.log
  examples/log/bipedal_walk_invdyn.log
  examples/log/bipedal_walk_ubound.log
  examples/log/humanoid_manipulation.log
  examples/log/humanoid_taichi.log
  examples/log/quadrupedal_gaits_fwddyn.log
  examples/log/quadrupedal_gaits_invdyn.log
  examples/log/quadrupedal_walk_ubound.log
  include/crocoddyl/core/costs/residual.hpp
  include/crocoddyl/core/costs/residual.hxx
  include/crocoddyl/core/residual-base.hpp
  include/crocoddyl/core/residual-base.hxx
  include/crocoddyl/multibody/residuals/state.hpp
  include/crocoddyl/multibody/residuals/state.hxx
Labels: enhancement, design library, efficiency
