Repository loco-3d/crocoddyl, pull requests merged in 2024-09, with the labels that each got.

#1294 Replaced selfadjointView to enhace efficiency
  CHANGELOG.md
  include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
Labels: enhancement

#1296 Nix
  .github/workflows/nix.yml
  README.md
  flake.lock
  flake.nix
Labels: no changelog

#1298 Support Pinocchio 2.6.20 >
  CMakeLists.txt
  bindings/python/crocoddyl/__init__.py
  examples/log/update_logfiles.sh
  include/crocoddyl/multibody/contacts/contact-1d.hxx
  include/crocoddyl/multibody/contacts/contact-2d.hxx
  include/crocoddyl/multibody/contacts/contact-3d.hxx
  include/crocoddyl/multibody/contacts/contact-6d.hxx
  include/crocoddyl/multibody/contacts/multiple-contacts.hxx
  include/crocoddyl/multibody/impulses/impulse-3d.hxx
  include/crocoddyl/multibody/impulses/impulse-6d.hxx
  include/crocoddyl/multibody/impulses/multiple-impulses.hxx
  unittest/bindings/factory.py
  unittest/factory/cost.cpp
  unittest/factory/residual.cpp
Labels: dependencies, no changelog

#1300 Improved action factory used for unit testing
  CHANGELOG.md
  unittest/factory/action.cpp
  unittest/factory/action.hpp
  unittest/factory/solver.cpp
  unittest/factory/solver.hpp
  unittest/test_solvers.cpp
Labels: ci/cd

#1302 Returning update nh_T and ng_T dimensions
  include/crocoddyl/multibody/actions/contact-fwddyn.hpp
  include/crocoddyl/multibody/actions/contact-fwddyn.hxx
  include/crocoddyl/multibody/actions/contact-invdyn.hpp
  include/crocoddyl/multibody/actions/contact-invdyn.hxx
  include/crocoddyl/multibody/actions/free-fwddyn.hpp
  include/crocoddyl/multibody/actions/free-fwddyn.hxx
  include/crocoddyl/multibody/actions/free-invdyn.hpp
  include/crocoddyl/multibody/actions/free-invdyn.hxx
  include/crocoddyl/multibody/actions/impulse-fwddyn.hpp
  include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
  src/core/solver-base.cpp
Labels: clean-up, no changelog

#1307 Add Bounds to the Inequality Feasibility Calculation
  CHANGELOG.md
  include/crocoddyl/core/solver-base.hpp
  src/core/solver-base.cpp
Labels: bug, design library
