Repository loco-3d/crocoddyl, pull requests merged in 2025-03, with the labels that each got.

#1352 Fixed checking of positive semi-define condition in LQR problems
  CHANGELOG.md
  include/crocoddyl/core/actions/diff-lqr.hxx
  include/crocoddyl/core/actions/lqr.hxx
Labels: bug

#1353 Remove absolute path for boost library
  CHANGELOG.md
  CMakeLists.txt
Labels: clean-up

#1359 Update flake.lock
  .github/workflows/ros1-ci.yaml
  .github/workflows/ros2-ci.yaml
  dependencies.rosinstall
  flake.lock
Labels: no changelog

#1364 Fixing ROS CI in devel branch
  .github/workflows/ros2-ci.yaml
Labels: ci/cd, no changelog

#1369 Bugfix: Fix CMake error message during `python_build`
  CHANGELOG.md
  bindings/python/crocoddyl/CMakeLists.txt
Labels: bug
