Repository loco-3d/crocoddyl, pull requests merged in 2025-01, with the labels that each got.

#1334 Provide more efficient of profilers
  CMakeLists.txt
  include/crocoddyl/core/utils/stop-watch.hpp
  src/core/utils/stop-watch.cpp
Labels: no ros

#1337 Further improve profiler.
  include/crocoddyl/core/utils/stop-watch.hpp
  src/core/utils/stop-watch.cpp
Labels: no changelog, no ros

#1338 Changed return policy to be compliant with Pinocchio
  CHANGELOG.md
  bindings/python/crocoddyl/core/solvers/box-ddp.cpp
  bindings/python/crocoddyl/core/solvers/box-fddp.cpp
  bindings/python/crocoddyl/core/solvers/ddp.cpp
  bindings/python/crocoddyl/core/solvers/fddp.cpp
  bindings/python/crocoddyl/core/solvers/intro.cpp
  bindings/python/crocoddyl/core/solvers/kkt.cpp
Labels: bug, python, no ros
